apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: eszop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: arokasprz100/cart-service:latest
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        ports:
        - name: port
          containerPort: 8080
        env:
        - name: SERVICE_PORT
          value: "8080"
        - name: OFFERS_HOST
          value: "offers-service"
        - name: OFFERS_PORT
          value: "80"
        - name: ORDERS_HOST
          value: "orders-service"
        - name: ORDERS_PORT
          value: "80"
        - name: POSTGRES_HOST
          value: "eszop-db-service"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-password
        
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: eszop
spec:
  selector:
    app: cart
  ports:
  - name: port
    port: 80
    targetPort: 8080
