apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: eszop
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
    - protocol: TCP
      name: admin
      port: 8080
  selector:
    app: traefik
  type: LoadBalancer