apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: eszop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: loniowsky/authentication-service:latest
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          ports:
            - name: port
              containerPort: 8080
          env:
            - name: USERS_HOST
              value: users-service
            - name: USERS_PORT
              value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: eszop
spec:
  selector:
    app: authentication
  ports:
    - name: port
      port: 80
      targetPort: 8080
