apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: eszop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: loniowsky/eszop-frontend:debug
          resources:
            limits:
              memory: "500Mi"
              cpu: "300m"
          ports:
            - name: port
              containerPort: 80
          env:
            - name: REACT_APP_AUTH_SERVICE_URL
              value: <backend_url>
            - name: REACT_APP_OFFERS_SERVICE_URL
              value: <backend_url>
            - name: REACT_APP_ORDERS_SERVICE_URL
              value: <backend_url>
            - name: REACT_APP_CART_SERVICE_URL
              value: <backend_url>
            - name: REACT_APP_CHAT_SERVICE_URL
              value: <backend_url>
            - name: REACT_APP_CHAT_SERVICE_WS_URL
              value: <backend_url>

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: eszop
spec:
  selector:
    app: frontend
  ports:
    - name: port
      port: 80
      targetPort: 80
  type: LoadBalancer
