apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: eszop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: arokasprz100/payment-service:latest
        resources:
          limits:
            memory: "500Mi"
            cpu: "300m"
        ports:
        - name: port
          containerPort: 8080
        env:
        - name: SERVICE_PORT
          value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: eszop
spec:
  selector:
    app: payment
  ports:
  - name: port
    port: 80
    targetPort: 8080
