apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: eszop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: loniowsky/users-service:latest
          resources:
            limits:
              memory: "600Mi"
              cpu: "400m"
          ports:
            - name: port
              containerPort: 8080
          env:
            - name: SERVICE_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  namespace: eszop
spec:
  selector:
    app: users
  ports:
    - name: port
      port: 80
      targetPort: 8080
